name: hangman
description: "A subject-based Hangman word game built with Flutter and Flame."
publish_to: 'none'

version: 1.2.2+5

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.18.0
  google_fonts: ^6.2.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  google_mobile_ads: ^7.0.0
  url_launcher: ^6.1.10
  flame_audio: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.1.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icon.png


icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
